apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-js
data:
  data.js: |
    db = db.getSiblingDB('product-service');

    db.createCollection('products');

    db.products.insertMany(
    [
      {
        "name":"iphone",
        "price":"1000"
      },
      {
        "name":"ipad",
        "price":"800"
      }
    ])
	      
    
