apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: express-secret
type: Opaque
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4=
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ=
  #ME_CONFIG_MONGODB_SERVER: bW9uZ28=

