apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express-app
  ports:
  - port: 8081
    targetPort: 8081
